// Code generated by scripts/gen-components.py from components.allow. DO NOT EDIT.

//go:build !darwin

// Package components links the Redpanda Connect component packages that carry
// no Redpanda Community License code, registering them in the Benthos global
// environment as a side effect of being imported.
package components

import (
	_ "github.com/redpanda-data/connect/v4/public/components/tigerbeetle"
)
