// Code generated by scripts/gen-components.py from components.allow. DO NOT EDIT.

// Package unwrapped links Apache-2.0 implementation packages of Redpanda Connect
// directly, because the public wrapper upstream ships for each of them is not
// Apache-2.0, or imports packages that are not, and is therefore never imported.
package unwrapped

import (
	_ "github.com/redpanda-data/connect/v4/internal/impl/awk"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/bedrock"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/cloudwatch"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/kinesis"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/lambda"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/s3"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/sns"
	_ "github.com/redpanda-data/connect/v4/internal/impl/aws/sqs"
	_ "github.com/redpanda-data/connect/v4/internal/impl/cohere"
	_ "github.com/redpanda-data/connect/v4/internal/impl/html"
	_ "github.com/redpanda-data/connect/v4/internal/impl/jsonpath"
	_ "github.com/redpanda-data/connect/v4/internal/impl/lang"
	_ "github.com/redpanda-data/connect/v4/internal/impl/mongodb/aws"
	_ "github.com/redpanda-data/connect/v4/internal/impl/ollama"
	_ "github.com/redpanda-data/connect/v4/internal/impl/openai"
	_ "github.com/redpanda-data/connect/v4/internal/impl/opensearch/aws"
	_ "github.com/redpanda-data/connect/v4/internal/impl/parquet"
	_ "github.com/redpanda-data/connect/v4/internal/impl/timeplus"
	_ "github.com/redpanda-data/connect/v4/internal/impl/xml"
)
