#!/usr/bin/env python3
"""Generates go-bridge/internal/components from go-bridge/components.allow.

The allowlist is the RCL boundary, so it is data rather than hand-written
imports: the bridge and the catalog tool both link this one package, which
keeps `go run ./internal/catalogtool` honest about what the shipped library
actually registers.

An allowlist entry may carry a Go build constraint after whitespace
(`tigerbeetle\t!darwin`). Entries are grouped by constraint, one generated file
each, so a package that cannot link on one platform does not cost every
platform.

Pass a different allowlist as argv[1] to build a subset while iterating.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = "github.com/redpanda-data/connect/v4/public/components"
OUTDIR = os.path.join(ROOT, "go-bridge", "internal", "components")

DOC = """// Package components links the Redpanda Connect component packages that carry
// no Redpanda Community License code, registering them in the Benthos global
// environment as a side effect of being imported.
"""


def read_allowlist(path):
    """Returns {build constraint or None: [package, ...]}."""
    groups = {}
    with open(path) as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            package, constraint = (line.split(None, 1) + [""])[:2]
            groups.setdefault(constraint.strip() or None, []).append(package)
    seen = [p for packages in groups.values() for p in packages]
    if len(seen) != len(set(seen)):
        raise SystemExit(f"{path}: duplicate entries")
    return {k: sorted(v) for k, v in groups.items()}


def filename(constraint):
    if constraint is None:
        return "components_gen.go"
    # "!darwin" must not become "..._darwin_gen.go", which reads as the opposite.
    slug = re.sub(r"[^a-z0-9]+", "_", constraint.lower().replace("!", "not ")).strip("_")
    return f"components_{slug}_gen.go"


def render(source, constraint, packages):
    out = f"// Code generated by scripts/gen-components.py from {source}. DO NOT EDIT.\n\n"
    if constraint:
        out += f"//go:build {constraint}\n\n"
    out += DOC + "package components\n\nimport (\n"
    out += "".join(f'\t_ "{MODULE}/{p}"\n' for p in packages)
    return out + ")\n"


def main():
    name = sys.argv[1] if len(sys.argv) > 1 else "components.allow"
    groups = read_allowlist(os.path.join(ROOT, "go-bridge", name))

    os.makedirs(OUTDIR, exist_ok=True)
    keep = {}
    for constraint, packages in sorted(groups.items(), key=lambda kv: kv[0] or ""):
        target = filename(constraint)
        if target in keep:
            raise SystemExit(
                f"constraints {keep[target]!r} and {constraint!r} both map to {target}; "
                "give one of them a distinct spelling"
            )
        keep[target] = constraint
        with open(os.path.join(OUTDIR, target), "w") as handle:
            handle.write(render(name, constraint, packages))
        print(f"{target}: {len(packages)} packages" + (f" ({constraint})" if constraint else ""))

    for stale in os.listdir(OUTDIR):
        if stale.endswith("_gen.go") and stale not in keep:
            os.remove(os.path.join(OUTDIR, stale))
            print(f"{stale}: removed (no longer in {name})")


if __name__ == "__main__":
    main()
