#!/usr/bin/env python3
"""Generates go-bridge/internal/components from go-bridge/components.allow.

The allowlist is the RCL boundary, so it is data rather than hand-written
imports: the bridge and the catalog tool both link this one package, which
keeps `go run ./internal/catalogtool` honest about what the shipped library
actually registers.

An allowlist entry may carry a Go build constraint after whitespace
(`tigerbeetle\t!darwin`). Entries are grouped by constraint, one generated file
each, so a package that cannot link on one platform does not cost every
platform.

An entry under `internal/` names an Apache-2.0 implementation package whose
public wrapper cannot be used. Go forbids importing it from our module path, so
those entries are written into go-bridge/unwrapped, a nested module whose path
sits inside the upstream tree, and the components package imports that.

Pass a different allowlist as argv[1] to build a subset while iterating.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPSTREAM = "github.com/redpanda-data/connect/v4"
MODULE = UPSTREAM + "/public/components"
OUTDIR = os.path.join(ROOT, "go-bridge", "internal", "components")
UNWRAPPED = UPSTREAM + "/mqbridge/unwrapped"
UNWRAPPED_DIR = os.path.join(ROOT, "go-bridge", "unwrapped")

DOC = """// Package components links the Redpanda Connect component packages that carry
// no Redpanda Community License code, registering them in the Benthos global
// environment as a side effect of being imported.
"""

UNWRAPPED_DOC = """// Package unwrapped links Apache-2.0 implementation packages of Redpanda Connect
// directly, because the public wrapper upstream ships for each of them is not
// Apache-2.0, or imports packages that are not, and is therefore never imported.
"""


def read_allowlist(path):
    """Returns {build constraint or None: [package, ...]}."""
    groups = {}
    with open(path) as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            package, constraint = (line.split(None, 1) + [""])[:2]
            groups.setdefault(constraint.strip() or None, []).append(package)
    seen = [p for packages in groups.values() for p in packages]
    if len(seen) != len(set(seen)):
        raise SystemExit(f"{path}: duplicate entries")
    return {k: sorted(v) for k, v in groups.items()}


def filename(constraint):
    if constraint is None:
        return "components_gen.go"
    # "!darwin" must not become "..._darwin_gen.go", which reads as the opposite.
    slug = re.sub(r"[^a-z0-9]+", "_", constraint.lower().replace("!", "not ")).strip("_")
    return f"components_{slug}_gen.go"


def render(source, constraint, package, doc, imports):
    out = f"// Code generated by scripts/gen-components.py from {source}. DO NOT EDIT.\n\n"
    if constraint:
        out += f"//go:build {constraint}\n\n"
    out += doc + f"package {package}\n\nimport (\n"
    out += "".join(f'\t_ "{path}"\n' for path in imports)
    return out + ")\n"


def write(source, outdir, package, doc, groups):
    """Writes one generated file per build constraint and drops stale ones."""
    os.makedirs(outdir, exist_ok=True)
    keep = {}
    for constraint, imports in sorted(groups.items(), key=lambda kv: kv[0] or ""):
        target = filename(constraint)
        if target in keep:
            raise SystemExit(
                f"constraints {keep[target]!r} and {constraint!r} both map to {target}; "
                "give one of them a distinct spelling"
            )
        keep[target] = constraint
        with open(os.path.join(outdir, target), "w") as handle:
            handle.write(render(source, constraint, package, doc, imports))
        label = os.path.join(os.path.basename(outdir), target)
        print(f"{label}: {len(imports)} packages" + (f" ({constraint})" if constraint else ""))

    for stale in os.listdir(outdir):
        if stale.endswith("_gen.go") and stale not in keep:
            os.remove(os.path.join(outdir, stale))
            print(f"{stale}: removed (no longer in {source})")


def main():
    name = sys.argv[1] if len(sys.argv) > 1 else "components.allow"
    groups = read_allowlist(os.path.join(ROOT, "go-bridge", name))

    public, internal = {}, {}
    for constraint, packages in groups.items():
        for package in packages:
            if package.startswith("internal/"):
                internal.setdefault(constraint, []).append(f"{UPSTREAM}/{package}")
            else:
                public.setdefault(constraint, []).append(f"{MODULE}/{package}")
    if internal:
        public[None] = sorted(public.get(None, []) + [UNWRAPPED])

    write(name, OUTDIR, "components", DOC, public)
    write(name, UNWRAPPED_DIR, "unwrapped", UNWRAPPED_DOC, internal)


if __name__ == "__main__":
    main()
