#!/usr/bin/env bash
# Render the Homebrew formula for a given release, with real sha256s pulled from
# the published GitHub release assets, into <outdir>/Formula/mq-bridge-connect.rb.
# It does not push anything: the caller copies the output into marcomq/homebrew-tap.
#
# Usage:
#   render.sh <tag> [repo] [outdir]
#     tag       release tag, e.g. v0.1.0   (required)
#     repo      owner/name  (default: marcomq/mq-bridge-connect)
#     outdir    where to write Formula/ (default: ./out)
set -euo pipefail

TAG="${1:?usage: render.sh <tag> [repo] [outdir]}"
REPO="${2:-marcomq/mq-bridge-connect}"
OUTDIR="${3:-out}"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

sha() {
  local sum
  if command -v sha256sum >/dev/null 2>&1; then sum="sha256sum"; else sum="shasum -a 256"; fi
  curl -fsSL "${BASE}/mq-bridge-connect-${VERSION}-$1.tar.gz" | $sum | cut -d' ' -f1
}

echo "resolving checksums for ${REPO} ${TAG} ..." >&2
MAC_ARM="$(sha aarch64-apple-darwin)"
LINUX_X64="$(sha x86_64-unknown-linux-gnu)"
LINUX_ARM64="$(sha aarch64-unknown-linux-gnu)"

mkdir -p "${OUTDIR}/Formula"

cat > "${OUTDIR}/Formula/mq-bridge-connect.rb" <<RUBY
# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in marcomq/mq-bridge-connect — do not edit by hand.
class MqBridgeConnect < Formula
  desc "Unofficial Redpanda Connect compatibility plugin for mq-bridge"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${BASE}/mq-bridge-connect-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/mq-bridge-connect-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X64}"
    end
    on_arm do
      url "${BASE}/mq-bridge-connect-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    # Both libraries share one directory: the plugin loads its Go sibling from
    # beside itself. \$HOMEBREW_PREFIX/lib/mq-bridge is on mq-bridge's search path.
    (lib/"mq-bridge").install Dir["libmq_bridge_connect*"]
    doc.install "THIRD_PARTY_NOTICES", "LICENSE-MIT", "LICENSE-APACHE", "INSTALL.md"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_connect.#{ext}", :exist?
    assert_predicate lib/"mq-bridge/libmq_bridge_connect_go.#{ext}", :exist?
    assert_predicate doc/"THIRD_PARTY_NOTICES", :exist?
  end
end
RUBY

echo "wrote ${OUTDIR}/Formula/mq-bridge-connect.rb" >&2
